GET http://localhost:3000/api/practice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImN1cnJlbnRVc2VyIjp7ImlkIjoyLCJlbWFpbCI6Im1hcmtAYmFjaC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCRTamZscEdYZ2Zzc0pJc3JPSzZOdkF1YnRjNms2dUViVnpwS1JUWmNIdDAybzlLdW1lZXNtLiJ9fSwiaWF0IjoxNjQ0MDAyOTE5fQ.TG0ALqAI5zOp6p_01_8rD_DuuO1_8stbF_ylhqFhDVc

###

POST http://localhost:3000/api/practice
Content-Type: application/json

{
  "scale": "C#",
  "bpm": 75,
  "userId": 1
}

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "joe@satrian.com",
  "password": "password"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "mark@bach.com",
  "password": "password"
}